export const SET_CURRENT_JSON_FILE = "SET_CURRENT_JSON_FILE";
export const SET_CURRENT_JSON_CODE = "SET_CURRENT_JSON_CODE";
export const SET_LOADING = "SET_LOADING";
export const SET_CURRENT_MODE = "SET_CURRENT_MODE";
export const SET_CURRENT_TAG_TO_EDIT = "SET_CURRENT_TAG_TO_EDIT"
export const SET_EDITED_TAG = "SET_EDITED_TAG"
export const RESET_STATE = "RESET_STATE"